select cliente.NM_CLIENTE,	
pedido.CD_PEDIDO,
pedido.DT_PEDIDO
from CLIENTE join PEDIDO
on CLIENTE.CD_CLIENTE= PEDIDO.CD_CLIENTE

select cliente.NM_CLIENTE,	
pedido.CD_PEDIDO,
pedido.DT_PEDIDO,
ITEM_PEDIDO.CD_PRODUTO,
ITEM_PEDIDO.QT_PRODUTO
from CLIENTE join PEDIDO
on CLIENTE.CD_CLIENTE= PEDIDO.CD_CLIENTE
join ITEM_PEDIDO
on PEDIDO.CD_PEDIDO = ITEM_PEDIDO.CD_PEDIDO

select cliente.NM_CLIENTE,	
pedido.CD_PEDIDO,
pedido.DT_PEDIDO,
ITEM_PEDIDO.CD_PRODUTO,
ITEM_PEDIDO.QT_PRODUTO,
PRODUTO.DS_PRODUTO
from CLIENTE join PEDIDO
on (CLIENTE.CD_CLIENTE= PEDIDO.CD_CLIENTE)
join ITEM_PEDIDO
on PEDIDO.CD_PEDIDO = ITEM_PEDIDO.CD_PEDIDO
join PRODUTO
on(ITEM_PEDIDO.CD_PRODUTO= PRODUTO.CD_PRODUTO)
