SELECT GETDATE();

select DATEPART(week, GETDATE());

select DATEPART(DY, GETDATE());

select DATEPART(YY, GETDATE());

select DATENAME(WEEKDAY, GETDATE());
select DATENAME(WEEKDAY, '2005-05-29');

select NOME, DATENAME(WEEKDAY, ADMISSAO) FROM CADFUN;

select AVG(FILHOS) AS MEDIA_FILHOS FROM CADFUN

select AVG(FILHOS) AS MEDIA_FILHOS FROM CADFUN WHERE DEPTO= 5
