CREATE DATABASE CLIENTE LOJA2023;
  USE LOJA2023;
   
   
   CREATE TABLE CLIENTE(
     CD_CLIENTE INT NOT NULL PRIMARY KEY,
     NM_CLIENTE VARCHAR(30),
     DS_CIDADE VARCHAR(30),
     DS_UF VARCHAR(2)
     );
    
	CREATE TABLE PEDIDO(
	CD_PEDIDO INT NOT NULL PRIMARY KEY,
	DT_PEDIDO DATETIME,
	CD_CLIENTE INT
	); 
	
	CREATE TABLE PRODUTO(
	CD_PRODUTO INT NOT NULL PRIMARY KEY,
	DS_PRODUTO VARCHAR(50)
	);
	
	CREATE TABLE ITEM_PEDIDO(
	CD_PEDIDO INT,
	CD_PRODUTO INT,
	QT_PRODUTO INT
	);
	
	SELECT *FROM CLIENTE;