use VIRTUAL_FINAL

--SELECIONA TODAS AS COLUNAS DA TABELA CADFUN
select *from CADFUN;

--SELECIONA APENAS AS COLUNAS NOME, SALARIO DA TABELA CADFUN
select NOME, SALARIO FROM CADFUN;

--SELECIONA APENAS AS COLUNAS CODIGO, NOME E FUNCAO DA TABELA CADFUN
select CODFUN, NOME, FUNCAO FROM CADFUN;

--SELECIONA APENAS AS COLUNAS CODIGO, NOME E FUNCAO EM ORDEM CRESCENTE DE NOME
select CODFUN, NOME, FUNCAO FROM CADFUN 
ORDER BY NOME;-- ESTA LINHA FAZ A ORDENAÇÃO

--SELECIONA AS COLUNAS NOME, DEPTO E SALARIO DO DEPARTAMENTO 3
SELECT NOME, DEPTO, SALARIO FROM CADFUN WHERE DEPTO= 
'3'--usa as aspas simples quando a coluna for texto char, varchar ou date

--SELECIONA NOME, SALARIO, FUNCAO E FILTRA FUNCAO DE SOMENTE VENDEDOR
SELECT NOME, SALARIO, FUNCAO FROM CADFUN WHERE FUNCAO= 'VENDEDOR'

--SELECIONA NOME, SALARIO E FUNCAO E FILTRA OS SALARIOS ACIMA DE 2000
SELECT NOME, SALARIO, FUNCAO FROM CADFUN WHERE SALARIO >=2000.00;


