select CODFUN, NOME, FUNCAO FROM CADFUN WHERE SALARIO > 1500

--VIZUALIZAÇÃO (VIEW)
--TABELA VIRTUAL

CREATE VIEW TABELARESUMO AS 
SELECT CODFUN, NOME, FUNCAO FROM CADFUN
WHERE SALARIO > 1500; 
------------------------------------------------------------------------------
SELECT NOME, CIDADE, ESTADO
FROM CLIENTE
WHERE ESTADO= 'RJ' OR ESTADO= 'SP'
----OU----
SELECT NOME, CIDADE, ESTADO
FROM CLIENTE
WHERE ESTADO IN ('SP', 'RJ')
----CRIAR VIEW----
CREATE VIEW CLIENTE_SUDESTE AS
SELECT NOME, CIDADE, ESTADO
FROM CLIENTE 
WHERE ESTADO = 'SP' OR ESTADO = 'RJ'
----APAGAR VIEW----
DROP VIEW CLIENTE_SUDESTE
----VIZUALIZAR A VIEW-----
SELECT * FROM CLIENTE_SUDESTE
----VIZUALIZAR SO DADOS DA VIEW----
SELECT CIDADE FROM CLIENTE_SUDESTE
SELECT NOME FROM CLIENTE_SUDESTE
SELECT ESTADO FROM CLIENTE_SUDESTE