SELECT NOME, SALARIO FROM CADFUN

SELECT NOME, SALARIO + 5000 FROM CADFUN

SELECT NOME, SALARIO, SALARIO + 5000 AS SALARIO_NEW FROM CADFUN

SELECT NOME,SALARIO, SALARIO+ 5000 AS SALARIO_NEW, SALARIO,  CONVERT(DECIMAL(10,2), SALARIO * 1.10) AS SALARIO_PORCNT FROM CADFUN
